### ISSUE TITLE
Ease .gitlint rules

### ISSUE THREAD

**Issue by 0Grit** [golioth/zephyr-sdk#112]

**Comment by 0Grit** [comment]
@mniestroj I'd like to ease the gitlint restrictions where it makes sense.
* I still want to enforce rebase & squash before merge but not in CI if possible
* I'd like to eliminate the requirement of each commit in the PR having an extended description
* I'm open to looking into how we could enforce an extended description upon squash&merge

What are your thoughts?

**Comment by mniestroj** [comment]
>I still want to enforce rebase & squash before merge but not in CI if possible

squashing commits before doing merge results in loosing valuable information from git history. The main purpose to split changes to separate git commits is in order to keep good description of why each change was made, why it shouldn't be dropped at some (or why it should if it is temporarily fixing some issue), why it was implemented one way and not the other. Good git history the next as valuable information (IMO is even more valuable) as code comments and function descriptions.

>I'd like to eliminate the requirement of each commit in the PR having an extended description

As stated above, extended commit description serves a very valuable documentation purpose. This is valuable for developers trying to follow code changes over time, which is especially helpful when debugging things that worked fine and were broken over time. Extended commit description is also a requirement for making tools like `git blame`, `git log` and `git bisect` actually work. Those tools are extremely important when maintaining community projects with multiple contributors.

**Comment by 0Grit** [comment]
I have badly mis-interpreted the convention here.
I had thought we were squashing all work done within a PR into one commit that had an extended description of the changes.

You are saying only squash the work within a PR that comes together to make a distinct buildable change? (Which makes far more sense)

**Comment by vitprajzler** [comment]
Since this has no description, it's difficult for me to judge the priority of these changes, or if any changes are justified. 

What are the changes you are planning to make to the rules?
