### ISSUE TITLE
Use submanifests to make it easier to add Golioth to a project

### ISSUE THREAD

**Issue by beriberikix** [golioth/zephyr-sdk#32]
https://github.com/zephyrproject-rtos/zephyr/pull/37155

Once merged, we should change our configuration to take advantage of this better UX.

**Comment by vitprajzler** [comment]
@mniestroj - this is an older issue. Is this still relvant?

**Comment by mniestroj** [comment]
"submanifests" only works with vanilla Zephyr, not with NCS. With vanilla Zephyr we just recommend to setup west workspace with our SDK as root manifest repository. That way Zephyr is pulled as dependency. Setup with NCS on the other hand is done in a way that NCS is the root manifest repository (it controls all the subprojects, dependencies, etc.) and our SDK is pulled just a dependency (not the root main repository). If useful, then submanifests would be needed with NCS rather than vanilla Zephyr. That is however not supported in NCS.

I think we can close this issue.

**Comment by vitprajzler** [comment]
Got it, thank you for the explanation!
